vendor_id: 0x5a65726f
product_id: 0x00029252 
assign_activate: 0x0300   #DC synch register

auto_fault_reset: true
auto_enable_set: true

sdo:
  - {index: 0x6040, sub_index: 0, type: uint16, value: 0x80} # 清除错误

rpdo: #PxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x607a, sub_index: 0, type: int32, command_interface: position, default: .nan, factor: 83442.867648821, offset: 0} 
      #target position	
      - {index: 0x60ff, sub_index: 0, type: int32, default: 500, factor: 83442.867648821}	#target velocity
      - {index: 0x6071, sub_index: 0, type: int16, default: 0, factor: 1.0}	#target torque
      - {index: 0x6072, sub_index: 0, type: int16, default: 500}	# Max torque
      - {index: 0x6040, sub_index: 0, type: uint16, default: 6}	# Control word
      - {index: 0x6060, sub_index: 0, type: uint8, default: 8}	# Control operation
      - {index: 0xf0ff, sub_index: 0, type: uint8}	# Dummy byte
    
tpdo:  #TxPDO = transmit PDO Mapping
  - index: 0x1a00
    channels:
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position, factor: 0.000011984247763, offset: 0} #Position actual value	
      - {index: 0x60F4, sub_index: 0, type: int32}	#Position Following error actual value
      - {index: 0x606c, sub_index: 0, type: int32, state_interface: velocity, factor: 0.000011984247763 }	# Velocity actual value
      - {index: 0x6077, sub_index: 0, type: int16, state_interface: effort, factor: 1.0 }	# Torque actual value
      - {index: 0x6041, sub_index: 0, type: uint16}	# State word
      - {index: 0x603f, sub_index: 0, type: uint16}	# Error code
      - {index: 0x6061, sub_index: 0, type: uint8}	        # Mode of operation display
      - {index: 0xf0ff, sub_index: 0, type: uint8}	        # dummy byte

sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}